plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cs.atto3probe'
    compileSdk 36

    defaultConfig {
        applicationId 'com.cs.atto3probe'
        minSdk 28
        targetSdk 36
        versionCode 2
        versionName '0.1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
