plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cs.atto3probe'
    compileSdk 35

    defaultConfig {
        applicationId 'com.cs.atto3probe'
        minSdk 26
        targetSdk 28
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
